UPDATE words AS w SET phonetic = v.ph
FROM (VALUES
  ('Norte', 'Directions', 'nor-te'),
  ('Sur', 'Directions', 'soor'),
  ('Este', 'Directions', 'es-te'),
  ('Oeste', 'Directions', 'o-es-te'),
  ('Izquierda', 'Directions', 'ees-kyer-da'),
  ('Derecha', 'Directions', 'de-re-cha'),
  ('Derecho', 'Directions', 'de-re-cho'),
  ('Detrás', 'Directions', 'de-tras'),
  ('Adelante', 'Directions', 'a-de-lan-te'),
  ('Arriba', 'Directions', 'a-ree-ba'),
  ('Abajo', 'Directions', 'a-ba-ho'),
  ('Cerca', 'Directions', 'ser-ka'),
  ('Lejos', 'Directions', 'le-hos'),
  ('Dentro', 'Directions', 'den-tro'),
  ('Fuera', 'Directions', 'fwe-ra'),
  ('Esquina', 'Directions', 'es-kee-na'),
  ('Mapa', 'Directions', 'ma-pa'),
  ('Camino', 'Directions', 'ka-mee-no'),
  ('Lado', 'Directions', 'la-do'),
  ('Al lado', 'Directions', 'al la-do'),
  ('Entre', 'Directions', 'en-tre'),
  ('Hacia', 'Directions', 'a-sya'),
  ('Piso', 'Directions', 'pee-so'),
  ('Escaleras', 'Directions', 'es-ka-le-ras'),
  ('Ascensor', 'Directions', 'as-sen-sor'),
  ('Dirección', 'Directions', 'dee-rek-syon'),
  ('Cruce', 'Directions', 'kroo-se'),
  ('Cuadra', 'Directions', 'kwa-dra'),
  ('Edificio', 'Directions', 'e-dee-fee-syo'),
  ('Parque', 'Directions', 'par-ke'),
  ('Centro', 'Directions', 'sen-tro'),
  ('Plaza', 'Directions', 'pla-sa'),
  ('Puente', 'Directions', 'pwen-te'),
  ('Letrero', 'Directions', 'le-tre-ro'),
  ('Vía', 'Directions', 'bee-a'),
  ('Tráfico', 'Directions', 'tra-fee-ko'),
  ('Semáforo', 'Directions', 'se-ma-fo-ro'),
  ('Paso', 'Directions', 'pa-so'),
  ('Vuelta', 'Directions', 'bwel-ta'),
  ('Regreso', 'Directions', 're-gre-so'),
  ('Llegada', 'Directions', 'ye-ga-da'),
  ('Destino', 'Directions', 'des-tee-no')
) AS v(sp, th, ph)
WHERE w.spanish = v.sp AND w.theme = v.th;
