UPDATE words AS w SET phonetic = v.ph
FROM (VALUES
  ('Hola', 'Greetings & Social', 'o-la'),
  ('Adiós', 'Greetings & Social', 'a-dee-os'),
  ('Buenos días', 'Greetings & Social', 'bwe-nos dee-as'),
  ('Buenas tardes', 'Greetings & Social', 'bwe-nas tar-des'),
  ('Buenas noches', 'Greetings & Social', 'bwe-nas no-ches'),
  ('¿Cómo estás?', 'Greetings & Social', 'ko-mo es-tas'),
  ('¿Qué tal?', 'Greetings & Social', 'ke tal'),
  ('Mucho gusto', 'Greetings & Social', 'moo-cho goos-to'),
  ('Por favor', 'Greetings & Social', 'por fa-bor'),
  ('Gracias', 'Greetings & Social', 'gra-syas'),
  ('De nada', 'Greetings & Social', 'de na-da'),
  ('Perdón', 'Greetings & Social', 'per-don'),
  ('Lo siento', 'Greetings & Social', 'lo syen-to'),
  ('Bienvenido', 'Greetings & Social', 'byen-be-nee-do'),
  ('Hasta luego', 'Greetings & Social', 'as-ta lwe-go'),
  ('Vale', 'Greetings & Social', 'ba-le'),
  ('Amigo', 'Greetings & Social', 'a-mee-go'),
  ('Señor', 'Greetings & Social', 'sen-yor'),
  ('Señora', 'Greetings & Social', 'sen-yo-ra'),
  ('Señorita', 'Greetings & Social', 'sen-yo-ree-ta'),
  ('¿Cuánto cuesta?', 'Greetings & Social', 'kwan-to kwes-ta'),
  ('Nombre', 'Greetings & Social', 'nom-bre'),
  ('Edad', 'Greetings & Social', 'e-dad'),
  ('Lugar', 'Greetings & Social', 'loo-gar'),
  ('Sí', 'Greetings & Social', 'see'),
  ('No', 'Greetings & Social', 'no'),
  ('Quizás', 'Greetings & Social', 'kee-sas'),
  ('Claro', 'Greetings & Social', 'kla-ro'),
  ('Mañana', 'Greetings & Social', 'man-ya-na'),
  ('Ayer', 'Greetings & Social', 'a-yer'),
  ('Hoy', 'Greetings & Social', 'oy'),
  ('Gente', 'Greetings & Social', 'hen-te'),
  ('Personal', 'Greetings & Social', 'per-so-nal'),
  ('Grupo', 'Greetings & Social', 'groo-po'),
  ('Pareja', 'Greetings & Social', 'pa-re-ha'),
  ('Vecino', 'Greetings & Social', 'be-see-no'),
  ('Invitado', 'Greetings & Social', 'een-bee-ta-do'),
  ('Felicidades', 'Greetings & Social', 'fe-lee-see-da-des'),
  ('Cumpleaños', 'Greetings & Social', 'koom-ple-an-yos'),
  ('Salud', 'Greetings & Social', 'sa-lood'),
  ('Ayuda', 'Greetings & Social', 'a-yoo-da'),
  ('Repita', 'Greetings & Social', 're-pee-ta'),
  ('Entiende', 'Greetings & Social', 'en-tyen-de'),
  ('Despacio', 'Greetings & Social', 'des-pa-syo'),
  ('Ahora', 'Greetings & Social', 'a-o-ra'),
  ('Entonces', 'Greetings & Social', 'en-ton-ses'),
  ('Luego', 'Greetings & Social', 'lwe-go'),
  ('Siempre', 'Greetings & Social', 'syem-pre'),
  ('Nunca', 'Greetings & Social', 'noon-ka'),
  ('Juntos', 'Greetings & Social', 'hoon-tos'),
  ('Solo', 'Greetings & Social', 'so-lo')
) AS v(sp, th, ph)
WHERE w.spanish = v.sp AND w.theme = v.th;
