export const VOCAB_THEMES = [
  { id: 1,  title: 'Greetings & Social' },
  { id: 2,  title: 'Food & Drink' },
  { id: 3,  title: 'Travel & Transport' },
  { id: 4,  title: 'Directions' },
  { id: 5,  title: 'Shopping & Money' },
  { id: 6,  title: 'Health & Emergencies' },
  { id: 7,  title: 'People & Relationships' },
  { id: 8,  title: 'Work & Study' },
  { id: 9,  title: 'Home & Daily Life' },
  { id: 10, title: 'Weather & Nature' },
  { id: 11, title: 'Time & Numbers' },
  { id: 12, title: 'Core Grammar' },
  { id: 13, title: 'Technology & Communication' },
  { id: 14, title: 'Leisure & Entertainment' },
  { id: 15, title: 'Descriptions & Opinions' },
  { id: 16, title: 'Body & Appearance' },
  { id: 17, title: 'Feelings & Emotions' },
]

export const VERB_CATEGORIES = [
  { id: 1, title: 'Verbs -AR',          verbFamily: 'regular-ar' },
  { id: 2, title: 'Core Verbs',          verbFamily: null },
  { id: 3, title: 'Stem-Changing O→UE', verbFamily: null },
  { id: 4, title: 'Stem-Changing E→IE', verbFamily: null },
  { id: 5, title: 'Stem-Changing E→I',  verbFamily: null },
  { id: 6, title: 'Spelling Change',     verbFamily: null },
  { id: 7, title: '-Go Verbs',           verbFamily: null },
  { id: 8, title: 'Regular -ER/-IR',     verbFamily: null },
  { id: 9, title: 'True Irregulars',     verbFamily: null },
]
