-- Add per-level incorrect and reset counters to user_verb_progress
ALTER TABLE user_verb_progress
  ADD COLUMN IF NOT EXISTS l1_incorrect    INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS l2_incorrect    INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS l3_incorrect    INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS l4_incorrect    INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS l1_resets       INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS l2_resets       INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS l3_resets       INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS l4_resets       INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS total_incorrect INTEGER NOT NULL DEFAULT 0;

-- Add per-stage incorrect and reset counters to user_word_progress
ALTER TABLE user_word_progress
  ADD COLUMN IF NOT EXISTS s1_incorrect    INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS s2_incorrect    INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS s3_incorrect    INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS s1_resets       INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS s2_resets       INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS s3_resets       INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS total_incorrect INTEGER NOT NULL DEFAULT 0;
